---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert zoom is installed
      ansible.builtin.assert:
        that:
          - "'zoom' in ansible_facts.packages"
