---
- hosts: all

  tasks:
    - name: all | /etc/environment
      ansible.builtin.template:
        src: environment.j2
        dest: /etc/environment
        owner: root
        group: root
        mode: "0644"
      become: true
      tags: [proxy]

    - name: all | requisitos para modulo apt
      ansible.builtin.apt:
        name: aptitude
        state: present
      become: true

    - name: all | requisitos para modulo apt_repository
      ansible.builtin.apt:
        name: python3-apt
        state: present
      become: true

    # --- Profile-based tool selection ---
    - name: all | load tool profile definitions
      ansible.builtin.include_vars:
        file: vars/tool_profiles.yml
      tags: [always]

    - name: all | compute active_tools from profiles
      ansible.builtin.set_fact:
        active_tools: >-
          {{ (active_profiles | map('extract', tool_profiles) | flatten
              | union(extra_tools | default([]))
              | difference(skip_tools | default([])))
              | unique | list }}
      when: active_profiles is defined
      tags: [always]

    - name: all | default active_tools to full profile (backward compatible)
      ansible.builtin.set_fact:
        active_tools: >-
          {{ tool_profiles['full']
              | difference(skip_tools | default([]))
              | unique | list }}
      when: active_profiles is not defined
      tags: [always]

    - name: all | compute install variables from active_tools
      ansible.builtin.set_fact:
        install_apt: true
        install_apt_fast: true
        install_actualiza_sistema: true
        install_mejora_performance: true
        install_escritorio: "{{ 'escritorio' in active_tools }}"
        install_zoom: "{{ 'zoom' in active_tools }}"
        install_ffmpeg: "{{ 'ffmpeg' in active_tools }}"
        install_openshot: "{{ 'openshot' in active_tools }}"
        install_snap: "{{ 'snap' in active_tools }}"
        install_eclipse: "{{ 'eclipse' in active_tools }}"
        install_netbeans: "{{ 'netbeans' in active_tools }}"
        install_telegram_desktop: "{{ 'telegram_desktop' in active_tools }}"
        install_slack: "{{ 'slack' in active_tools }}"
        install_bitwarden: "{{ 'bitwarden' in active_tools }}"
        install_microsoft_visualstudio_code: "{{ 'microsoft_visualstudio_code' in active_tools }}"
        install_mise_en_place: "{{ 'mise_en_place' in active_tools }}"
        install_sshfs_fuse: "{{ 'sshfs_fuse' in active_tools }}"
        install_rambox: "{{ 'rambox' in active_tools }}"
        install_tn3270_emulator: "{{ 'tn3270_emulator' in active_tools }}"
        install_flatpak: "{{ 'flatpak' in active_tools }}"
        install_codium: "{{ 'codium' in active_tools }}"
        install_aws: "{{ 'aws' in active_tools }}"
        install_ansible: "{{ 'ansible' in active_tools }}"
        install_git: "{{ 'git' in active_tools }}"
        install_git_credential_manager: "{{ 'git_credential_manager' in active_tools }}"
        install_terraform: "{{ 'terraform' in active_tools }}"
        install_terraform_docs: "{{ 'terraform_docs' in active_tools }}"
        install_terragrunt: "{{ 'terragrunt' in active_tools }}"
        install_virtualbox: "{{ 'virtualbox' in active_tools }}"
        install_vagrant: "{{ 'vagrant' in active_tools }}"
        install_packer: "{{ 'packer' in active_tools }}"
        install_goss: "{{ 'goss' in active_tools }}"
        install_govc: "{{ 'govc' in active_tools }}"
        install_docker: "{{ 'docker' in active_tools }}"
        install_prolog: "{{ 'prolog' in active_tools }}"
        install_racket: "{{ 'racket' in active_tools }}"
        install_pharo: "{{ 'pharo' in active_tools }}"
        install_tinyproxy: "{{ 'tinyproxy' in active_tools }}"
      tags: [always]

    - name: all | display active_tools
      ansible.builtin.debug:
        msg: "Active tools: {{ active_tools }}"
        verbosity: 1
      tags: [always]

    - name: all | configura APT
      ansible.builtin.include_role:
        name: apt
        apply:
          tags: [apt]
      when: install_apt | bool
      tags: [apt]

    - name: all | instala y configura apt_fast
      ansible.builtin.include_role:
        name: apt_fast
        apply:
          tags: [aptfast, apt]
      when: install_apt_fast | bool
      tags: [aptfast, apt]

    - name: all | actualiza paquetes en sistema
      ansible.builtin.include_role:
        name: actualiza_sistema
        apply:
          tags: [apt, upgrade]
      when: install_actualiza_sistema | bool
      tags: [apt, upgrade]

    - name: paquetes generales requisitos para instalar devops
      ansible.builtin.package:
        name:
          - jq
          - git
          - wget
          - curl
          - socat
          - unzip
        state: present
      become: true

    - name: all | pup Parsing HTML at the command line
      ansible.builtin.include_role:
        name: pup
        apply:
          tags:
            - pup
      tags: [pup]

    - name: all | mejora performance
      ansible.builtin.include_role:
        name: mejora_performance
        apply:
          tags: [performance]
      when: install_mejora_performance | bool
      tags: [performance]


    - name: all | configura locales
      ansible.builtin.include_role:
        name: locales
        apply:
          become: true
          tags:
            - locales
      tags:
        - locales
      vars:
        locales_present:
          - es_AR.UTF-8
          - en_US.UTF-8
        locales_language_packs_present:
          - language-pack-en
          - language-pack-en-base
          - language-pack-es
          - language-pack-es-base
        locales_default:
          lang: es_AR.UTF-8
        #lc_all: C
