---
- hosts: devops

  tasks:
    - name: devops | verifica si hay virtualizacion por hardware requerido para VMware Workstation
      ansible.builtin.command: egrep "svm|vmx" /proc/cpuinfo
      ignore_errors: true
      changed_when: false
      become: true
      register: hay_virtualizacion_register
      tags:
        - devops
        - vmware-workstation
        - virtualbox

##
# VMWARE Workstation no longer available for download without registration
#
#    # https://idroot.us/install-vmware-workstation-player-ubuntu-20-04/
#    - ansible.builtin.include_role:
#        name: vmware-workstation
#        apply:
#          become: true
#          environment: # https://communities.vmware.com/thread/620226
#            LC_ALL: "C"
#          tags:
#            - devops
#            - vmware-workstation
#      when: hay_virtualizacion_register is succeeded
#      vars:
#        workstation_tempdir: /var/cache/workstation-downloads
#      tags:
#        - devops
#        - vmware-workstation

- hosts: devops
  tasks:

#    - name: devops | desactiva vmware workstation
#      ansible.builtin.shell: |
#        update-rc.d vmware disable
#        update-rc.d vmware-workstation-server disable
#        update-rc.d vmware-USBArbitrator disable
#      when: hay_virtualizacion_register is succeeded
#      become: true
#      changed_when: false
#      tags:
#        - devops
#        - vmware-workstation

    - ansible.builtin.include_role:
        name: aws
        apply:
          tags:
            - devops
            - aws
      when: install_aws | bool
      tags:
        - devops
        - aws

    - ansible.builtin.include_role:
        name: ansible
        apply:
          tags:
            - devops
            - ansible
      when: install_ansible | bool
      tags:
        - devops
        - ansible

    - ansible.builtin.include_role:
        name: git
        apply:
          tags:
            - devops
            - git
      when: install_git | bool
      tags:
        - devops
        - git

    - ansible.builtin.include_role:
        name: git_credential_manager
        apply:
          tags:
            - devops
            - git_credential_manager
      when: install_git_credential_manager | bool
      tags:
        - devops
        - git_credential_manager

    - ansible.builtin.include_role:
        name: terraform
        apply:
          tags:
            - devops
            - terraform
      when: install_terraform | bool
      tags:
        - devops
        - terraform

    - ansible.builtin.include_role:
        name: terraform_docs
        apply:
          tags:
            - devops
            - terraform
            - terraform_docs
      when: install_terraform_docs | bool
      tags:
        - devops
        - terraform
        - terraform_docs

    - ansible.builtin.include_role:
        name: terragrunt
        apply:
          tags:
            - devops
            - terraform
            - terragrunt
      when: install_terragrunt | bool
      tags:
        - devops
        - terraform
        - terragrunt

    - ansible.builtin.include_role:
        name: virtualbox
        apply:
          tags:
            - devops
            - virtualbox
      when:
        - install_virtualbox | bool
        - hay_virtualizacion_register is succeeded
      vars:
        virtualbox_old_packages_to_remove:
          - virtualbox-dkms
          - virtualbox-5.1
          - virtualbox-5.2
          - virtualbox-6.0
          - virtualbox-6.1
        virtualbox_version_to_install: "virtualbox-7.0"
      tags:
        - devops
        - virtualbox

    - ansible.builtin.include_role:
        name: virtualbox
        apply:
          tags:
            - devops
            - virtualbox
      when:
        - install_virtualbox | bool
        - hay_virtualizacion_register is failed
      vars:
        virtualbox_old_packages_to_remove:
          - virtualbox-dkms
          - virtualbox-5.1
          - virtualbox-5.2
          - virtualbox-6.1
          - virtualbox-7.0
        virtualbox_version_to_install: "virtualbox-6.0"
      tags:
        - devops
        - virtualbox

    - ansible.builtin.include_role:
        name: vagrant
        apply:
          tags:
            - devops
            - vagrant
      when: install_vagrant | bool
      tags:
        - devops
        - vagrant

    - ansible.builtin.include_role:
        name: packer
        apply:
          tags:
            - devops
            - packer
      when: install_packer | bool
      tags:
        - devops
        - packer

    - ansible.builtin.include_role:
        name: goss
        apply:
          tags:
            - devops
            - goss
      when: install_goss | bool
      tags:
        - devops
        - goss

    - ansible.builtin.include_role:
        name: govc
        apply:
          tags:
            - devops
            - govc
      when: install_govc | bool
      tags:
        - devops
        - govc

    - ansible.builtin.include_role:
        name: docker
        apply:
          tags:
            - devops
            - docker
      when: install_docker | bool
      tags:
        - devops
        - docker
