---
- hosts: devops

  tasks:

    - name: devops | verifica si hay virtualizacion por hardware requerido para VMware Workstation
      command: egrep "svm|vmx" /proc/cpuinfo
      ignore_errors: True
      changed_when: False
      become: True
      register: hay_virtualizacion_register
      tags: 
        - devops
        - vmware-workstation
        - virtualbox

    - include_role:
        name: vmware-workstation
        apply:
          become: true
          environment: # https://communities.vmware.com/thread/620226
            LC_ALL: "C"
          tags:
            - devops
            - vmware-workstation
      when: hay_virtualizacion_register is succeeded
      vars:
        workstation_tempdir: /var/cache/workstation-downloads
      tags: 
        - devops
        - vmware-workstation


- hosts: devops

  tasks:

  - name: devops | desactiva vmware workstation
    shell: |
      update-rc.d vmware disable
      update-rc.d vmware-workstation-server disable
      update-rc.d vmware-USBArbitrator disable
    when: hay_virtualizacion_register is succeeded
    become: true
    changed_when: false
    tags: 
      - devops
      - vmware-workstation

  - include_tasks: tasks/devops_aws.yml
    tags: 
      - devops
      - aws

  - include_tasks: tasks/devops_ansible.yml
    tags: 
      - devops
      - ansible 

  - include_tasks: tasks/devops_git.yml
    tags: 
      - devops
      - git

  - include_tasks: tasks/devops_terraform.yml
    tags: 
      - devops
      - terraform

  - include_tasks: tasks/devops_terraform_docs.yml
    tags: 
      - devops
      - terraform
      - terraform-docs

  - include_tasks: tasks/devops_terragrunt.yml
    tags: 
      - devops
      - terraform
      - terragrunt

  - include_tasks: tasks/devops_virtualbox.yml
    when: hay_virtualizacion_register is succeeded
    vars:
      virtualbox_old_packages_to_remove: 
        - virtualbox-dkms
        - virtualbox-5.1
        - virtualbox-5.2
        - virtualbox-6.0
      virtualbox_version_to_install: "virtualbox-6.1"
    tags: 
      - devops
      - virtualbox

  - include_tasks: tasks/devops_virtualbox.yml
    when: hay_virtualizacion_register is failed
    vars:
      virtualbox_old_packages_to_remove: 
        - virtualbox-dkms
        - virtualbox-5.1
        - virtualbox-5.2
        - virtualbox-6.1
      virtualbox_version_to_install: "virtualbox-6.0"
    tags: 
      - devops
      - virtualbox

  - include_tasks: tasks/devops_vagrant.yml
    tags: 
      - devops
      - vagrant

  - include_tasks: tasks/devops_packer.yml
    tags: 
      - devops
      - packer

  - include_tasks: tasks/devops_goss.yml
    tags: 
      - devops
      - goss

  - include_tasks: tasks/devops_govc.yml
    tags: 
      - devops
      - govc

  - include_tasks: tasks/devops_docker.yml
    tags: 
      - devops
      - docker

