---
- hosts: devops

  tasks:
    - name: devops | verifica si hay virtualizacion por hardware requerido para VMware Workstation
      ansible.builtin.command: egrep "svm|vmx" /proc/cpuinfo
      ignore_errors: true
      changed_when: false
      become: true
      register: hay_virtualizacion_register
      tags:
        - devops
        - vmware-workstation
        - virtualbox

##
# VMWARE Workstation no longer available for download without registration
#
#    # https://idroot.us/install-vmware-workstation-player-ubuntu-20-04/
#    - ansible.builtin.include_role:
#        name: vmware-workstation
#        apply:
#          become: true
#          environment: # https://communities.vmware.com/thread/620226
#            LC_ALL: "C"
#          tags:
#            - devops
#            - vmware-workstation
#      when: hay_virtualizacion_register is succeeded
#      vars:
#        workstation_tempdir: /var/cache/workstation-downloads
#      tags:
#        - devops
#        - vmware-workstation

- hosts: devops
  tasks:

#    - name: devops | desactiva vmware workstation
#      ansible.builtin.shell: |
#        update-rc.d vmware disable
#        update-rc.d vmware-workstation-server disable
#        update-rc.d vmware-USBArbitrator disable
#      when: hay_virtualizacion_register is succeeded
#      become: true
#      changed_when: false
#      tags:
#        - devops
#        - vmware-workstation

    - ansible.builtin.include_tasks: tasks/devops_aws.yml
      when: "'aws' in active_tools"
      tags:
        - devops
        - aws

    - ansible.builtin.include_tasks: tasks/devops_ansible.yml
      when: "'ansible' in active_tools"
      tags:
        - devops
        - ansible

    - ansible.builtin.include_role:
        name: git
        apply:
          tags:
            - devops
            - git
      when: "'git' in active_tools"
      tags:
        - devops
        - git

    - ansible.builtin.include_tasks: tasks/devops_git_credential_manager.yml
      when: "'git-credential-manager' in active_tools"
      tags:
        - devops
        - git-credential-manager

    - ansible.builtin.include_tasks: tasks/devops_terraform.yml
      when: "'terraform' in active_tools"
      tags:
        - devops
        - terraform

    - ansible.builtin.include_tasks: tasks/devops_terraform_docs.yml
      when: "'terraform-docs' in active_tools"
      tags:
        - devops
        - terraform
        - terraform-docs

    - ansible.builtin.include_tasks: tasks/devops_terragrunt.yml
      when: "'terragrunt' in active_tools"
      tags:
        - devops
        - terraform
        - terragrunt

    - ansible.builtin.include_tasks: tasks/devops_virtualbox.yml
      when:
        - "'virtualbox' in active_tools"
        - hay_virtualizacion_register is succeeded
      vars:
        virtualbox_old_packages_to_remove:
          - virtualbox-dkms
          - virtualbox-5.1
          - virtualbox-5.2
          - virtualbox-6.0
          - virtualbox-6.1
        virtualbox_version_to_install: "virtualbox-7.0"
      tags:
        - devops
        - virtualbox

    - ansible.builtin.include_tasks: tasks/devops_virtualbox.yml
      when:
        - "'virtualbox' in active_tools"
        - hay_virtualizacion_register is failed
      vars:
        virtualbox_old_packages_to_remove:
          - virtualbox-dkms
          - virtualbox-5.1
          - virtualbox-5.2
          - virtualbox-6.1
          - virtualbox-7.0
        virtualbox_version_to_install: "virtualbox-6.0"
      tags:
        - devops
        - virtualbox

    - ansible.builtin.include_tasks: tasks/devops_vagrant.yml
      when: "'vagrant' in active_tools"
      tags:
        - devops
        - vagrant

    - ansible.builtin.include_tasks: tasks/devops_packer.yml
      when: "'packer' in active_tools"
      tags:
        - devops
        - packer

    - ansible.builtin.include_tasks: tasks/devops_goss.yml
      when: "'goss' in active_tools"
      tags:
        - devops
        - goss

    - ansible.builtin.include_tasks: tasks/devops_govc.yml
      when: "'govc' in active_tools"
      tags:
        - devops
        - govc

    - ansible.builtin.include_tasks: tasks/devops_docker.yml
      when: "'docker' in active_tools"
      tags:
        - devops
        - docker
