---
- hosts: escritorio

  tasks:
    # TODO:
    # template para /etc/systemd/timesyncd.conf poner los servidores NTP
    # sudo service systemd-timesyncd restart

    - ansible.builtin.include_role:
        name: paquetes_de_escritorio
        apply:
          tags: [escritorio]
      when: install_escritorio | bool
      tags: [escritorio]

    - ansible.builtin.include_role:
        name: zoom
        apply:
          tags: [zoom]
      when: install_zoom | bool
      tags: [zoom]

    - ansible.builtin.include_role:
        name: ffmpeg
        apply:
          tags:
            - ffmpeg
            - video
      when: install_ffmpeg | bool
      tags: [ffmpeg, video]

    - ansible.builtin.include_role:
        name: openshot
        apply:
          tags: [openshot, video]
      when: install_openshot | bool
      tags: [openshot, video]

    - ansible.builtin.include_role:
        name: snap
        apply:
          tags:
            - escritorio
            - snap
      when: install_snap | bool
      tags:
        - escritorio
        - snap

    - ansible.builtin.include_role:
        name: eclipse
        apply:
          tags:
            - escritorio
            - eclipse
      when: install_eclipse | bool
      tags:
        - escritorio
        - eclipse

    - ansible.builtin.include_role:
        name: netbeans
        apply:
          tags:
            - escritorio
            - netbeans
      when: install_netbeans | bool
      tags:
        - escritorio
        - netbeans

    # Microsoft VisualStudio Code es version privativa, usaba VSCodium, el fork libre, me canse de los plugins que solo funcionan en vscode
    - ansible.builtin.include_role:
        name: microsoft_visualstudio_code
        apply:
          tags:
            - escritorio
            - microsoft_visualstudio_code
      when: install_microsoft_visualstudio_code | bool
      tags:
        - escritorio
        - microsoft_visualstudio_code

    - ansible.builtin.include_role:
        name: mise_en_place
        apply:
          tags:
            - escritorio
            - mise_en_place
      when: install_mise_en_place | bool
      tags:
        - escritorio
        - mise_en_place

    - ansible.builtin.include_role:
        name: codium
        apply:
          tags:
            - escritorio
            - codium
      when: install_codium | bool
      tags:
        - escritorio
        - codium

    - ansible.builtin.include_role:
        name: flatpak
        apply:
          tags:
            - escritorio
            - flatpak
      when: install_flatpak | bool
      tags:
        - escritorio
        - flatpak

    - ansible.builtin.include_role:
        name: sshfs_fuse
        apply:
          tags: [escritorio]
      when: install_sshfs_fuse | bool
      tags: [escritorio]

    - ansible.builtin.include_role:
        name: rambox
        apply:
          tags: [rambox]
      when: install_rambox | bool
      tags: [rambox]

    # - ansible.builtin.include_role:  # no funciona correctamente sobre ubuntu 18.04 (2019/02/06)
    #     name: liveusb_multiboot
    #     apply:
    #       tags: [multiboot]
    #   tags: [multiboot]

#    - ansible.builtin.include_role:
#        name: claude_code
#        apply:
#          become: true
#          tags:
#            - escritorio
#            - claude-code
#      tags:
#        - escritorio
#        - claude-code

    - ansible.builtin.include_role:
        name: tn3270_emulator
        apply:
          tags: [tn3270_emulator]
      when: install_tn3270_emulator | bool
      tags: [tn3270_emulator]
      # se usa para conectarse a minis y mainframes IBM
