---
- hosts: ocsinventoryagent
  become: true

  tasks:
    - name: ocsinventory-agent | incluye role
      ansible.builtin.include_role:
        name: ocsinventory-agent
        apply:
          tags: [ocsinventory-agent]
      when: ocs_server is defined and ocs_server | length > 0
      tags: [always]

    - name: ocsinventory-agent | elimina el paquete APT
      ansible.builtin.apt:
        name: ocsinventory-agent
        state: absent
        purge: true
      when: not (ocs_server is defined and ocs_server | length > 0)
      tags: [ocsinventory-agent]

    - name: ocsinventory-agent | elimina cron job
      ansible.builtin.cron:
        name: "Run OCS Inventory Agent"
        user: root
        state: absent
      when: not (ocs_server is defined and ocs_server | length > 0)
      tags: [ocsinventory-agent]

    - name: ocsinventory-agent | elimina repositorio APT
      ansible.builtin.apt_repository:
        repo: "deb http://deb.ocsinventory-ng.org/{{ ansible_distribution | lower }} stable main"
        filename: ocsinventory
        state: absent
      when: not (ocs_server is defined and ocs_server | length > 0)
      tags: [ocsinventory-agent]

    - name: ocsinventory-agent | elimina archivos del agente
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/apt/trusted.gpg.d/ocs-archive-keyring.gpg"
        - "/etc/ocsinventory"
        - "/var/log/ocsinventory-agent.log"
        - "/var/lib/ocsinventory-agent"
        # Legacy paths (old source-compiled agent)
        - "/etc/cron.d/ocsinventory-agent"
        - "/usr/local/bin/ocsinventory-agent"
      when: not (ocs_server is defined and ocs_server | length > 0)
      tags: [ocsinventory-agent]
