---
#- src: https://github.com/CesarBallardini/ansible-locales
- src: https://github.com/Oefenweb/ansible-locales
  version: v1.0.41
  scm: git
  name: locales

- src: https://github.com/CesarBallardini/Ansible-Role-For-UnixAgent
  version: cb-devel
  scm: git
  name: ocsinventory-agent

collections:
  - name: ansible.posix
  - name: community.general
