---
# Este playbook esta verificado en Ubuntu 22.04, 24.04, 26.04, Debian 13 (Bookworm), Debian 14 (Trixie)
#
# En caso de un nodo recien creado:
# export ANSIBLE_HOST_KEY_CHECKING=False
#
# time ansible-playbook -vv -i hosts site.yml --limit localhost

- import_playbook: all.yml
- import_playbook: escritorio.yml
- import_playbook: utn.yml
- import_playbook: devops.yml
- import_playbook: tinyproxy.yml
- import_playbook: ocsinventory-agent.yml
