---
# Este playbook esta verificado en Ubuntu 22.04 (Jammy), 24.04 (Noble), 26.04 (Resolute), Debian 13 (Trixie), Debian 14 (Forky)
#
# En caso de un nodo recien creado:
# export ANSIBLE_HOST_KEY_CHECKING=False
#
# time ansible-playbook -vv -i hosts site.yml --limit localhost

- import_playbook: all.yml
- import_playbook: escritorio.yml
- import_playbook: utn.yml
- import_playbook: devops.yml

- hosts: tinyproxy
  tasks:
    - name: tinyproxy | instala y configura tinyproxy
      ansible.builtin.include_role:
        name: tinyproxy
        apply:
          tags: [tinyproxy, proxy]
      when: install_tinyproxy | bool
      tags: [tinyproxy, proxy]

- import_playbook: ocsinventory-agent.yml
