---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: apt

    - name: Assert codium is installed
      ansible.builtin.assert:
        that:
          - "'codium' in ansible_facts.packages"
        fail_msg: "codium is not installed"
        success_msg: "codium is installed"
