---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check bw snap is installed
      ansible.builtin.command: snap list bw
      register: bw_snap
      failed_when: false
      changed_when: false

    - name: Assert bw snap is installed
      ansible.builtin.assert:
        that:
          - bw_snap.rc == 0
      ignore_errors: "{{ lookup('env', 'CI') | default(false) | bool }}"

    - name: Check bitwarden snap is installed
      ansible.builtin.command: snap list bitwarden
      register: bitwarden_snap
      failed_when: false
      changed_when: false

    - name: Assert bitwarden snap is installed
      ansible.builtin.assert:
        that:
          - bitwarden_snap.rc == 0
      ignore_errors: "{{ lookup('env', 'CI') | default(false) | bool }}"
