---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check terraform-docs exists
      ansible.builtin.command: /usr/local/bin/terraform-docs --version
      register: terraform_docs_check
      failed_when: false
      changed_when: false

    - name: Assert terraform-docs is installed
      ansible.builtin.assert:
        that:
          - terraform_docs_check.rc == 0
